---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: manufacturing-cluster
  region: ap-south-1


fargateProfiles:
  - name: fp-all
    selectors:
      - namespace: default
      - namespace: kube-system
      - namespace: application
      - namespace: cert-manager