apiVersion: v1
kind: Service
metadata:
  name: service-package
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: package-service